repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.4.2 # Use the latest stable version compatible with your Python
    hooks:
    -   id: black
        language_version: python3 # Specify python version

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0 # Use the latest stable version
    hooks:
    -   id: flake8
        args: [--max-line-length=88, --extend-ignore=E203] # Ignore E203 which conflicts with black 