name: Python CI

on:
  push:
    branches: [ main ] # Adjust branch name if needed
  pull_request:
    branches: [ main ] # Adjust branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest 